//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::bakery::Entity as Bakery;
pub use super::bread::Entity as Bread;
pub use super::bread_sale::Entity as BreadSale;
pub use super::chef::Entity as Chef;
