//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "employment_status")]
pub enum EmploymentStatus {
    #[sea_orm(string_value = "full_time")]
    FullTime,
    #[sea_orm(string_value = "part_time")]
    PartTime,
}
